### ISSUE TITLE
SyntaxFactory string literals incorrectly output nodes

### ISSUE THREAD

**Issue by TheGreatSageEqualToHeaven** [LorettaDevs/Loretta#91] opened 2022-08-08 22:41 UTC
**Describe the bug**
When creating a string literal node with the `SyntaxFactory` the inputted stirng

**To Reproduce**
Run
```cs
        Console.WriteLine(SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(@"Hi From
        Loretta
        ")).ToFullString());
```

**Expected behavior**
The node should output
```
Hi From
        Loretta
        
```

but outputs
```
"Hi\u{0020}From\r\n\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}Loretta\r\n\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}\u{0020}"
```

**Comment by GGG-KILLER** [comment] 2022-08-08 22:45
Duplicate of #89.

**Closed by GGG-KILLER** 2022-08-08 22:45 UTC
Labels: bug, version-Luau, version-Lua5.1, version-Lua5.2, version-Lua5.3, version-LuaJIT2.1, version-Lua5.4, version-FiveM, version-LuaJIT2.0
